{{- if include "llm-proxy.createSecret" . }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "llm-proxy.fullname" . }}-secret
  labels:
    {{- include "llm-proxy.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- if and (not .Values.database.existingSecret) .Values.database.url }}
  DB_URL: {{ .Values.database.url | quote }}
  {{- end }}
  {{- if and (not .Values.adminKey.existingSecret) .Values.adminKey.value }}
  ADMIN_KEY: {{ .Values.adminKey.value | quote }}
  {{- end }}
{{- end }}
